### ISSUE TITLE
Include docker compose file for testing

### ISSUE THREAD

**Issue by flaherts** [TIBCOSoftware/spotfire-cloud-deployment-kit#10]
Hello,

Would it be possible to include a simple docker compose file to run and test these images without the need for a full kubernetes install?

Kind regarads,
Sean

**Comment by mdiez-tibco** [comment]
This repository provides recipes for building container images and Helm charts for TIBCO Spotfire.

We focus on Kubernetes because it is predominant in the [CNCF landscape](https://landscape.cncf.io/), and it is endorsed by the major cloud service providers and many third party providers offering custom K8s certified distributions, installers, hosted Kubernetes, and as Kubernetes as a Service (KaaS). Nowadays, Kubernetes is the clear orchestrator of choice for enterprises.

Anyhow, you can build the TIBCO Spotfire container images using the provided container recipes. And you can deploy them on any container platform of your choice that supports OCI container images (for example Portainer, Docker Swarm, Nomad, Mesos. etc.).

Note that, in this case, you need to manage the integration with that container platform by yourself. We do not plan to provide recipes for orchestrating containers on other container platforms than Kubernetes.
