### ISSUE TITLE
Debian base image issue

### ISSUE THREAD

**Issue by ddasml** [TIBCOSoftware/spotfire-cloud-deployment-kit#11]
Debian package manager apt connects to http://deb.debian.org while apt-get update is run.
Azure firewall Security policy does not allow outbound http request and hence spotfire-base image is not getting created via azure DevOps pipeline.
Is there any workaround to overcome this issue?
If you suggest any other base image, please mention that as well.

Thanks,
Debasish Das

**Comment by mblixter** [comment]
It is not common for apt-get to use HTTPS. There's a lot of threads about this online, one being https://askubuntu.com/questions/146108/how-to-use-https-with-apt-get
We use the official Debian "stable-slim" image as the base image, and this image is configured by Debian to use the HTTP repos.
Since our images are based on the Debian base images, I cannot recommend another image for you. You are however welcome to modify the docker files yourself, and experiment with other images. We have not tested other images than the Debian stable-slim image.
I would suggest looking into allowing the repo URL's through the Azure firewall. I think this will be the easiest path forward.

//Morten
