### ISSUE TITLE
Default SDN are not installed on Spotfire Server once started 

### ISSUE THREAD

**Issue by alexandrev** [TIBCOSoftware/spotfire-cloud-deployment-kit#4]
Currently, the default SDN  (Spotfire.Dxp.netcore-linux.sdn Spotfire.Dxp.sdn ) are not being properly loaded in the launch of the Spotfire server, and you need to provided it manually. Currently spotfire-config is not loaded those files even that they are provided to the build script. 

Spotfire Config needs to change to include those SDN as they are doing for Web Player and Automation Services to be able to deploy it later.

**Comment by mdiez-tibco** [comment]
Hi @alexandrev, 

What you described is how it currently works. 

Deployments are not automatically uploaded. When you install a spotfire-server and create a new spotfire-database it will start with an empty deployment area. The services don't need the sdn/spk files because they already are pre-built with all the packages in their respective container images, however they will refuse to start due to a license check that won't pass unless the right packages are deployed to the deployment area.  For example, the spotfire-webplayer container won't start without the proper deployment packages in the deployment area. This is noted in the respective READMEs.
 
You can however deploy several deployment packages automatically with the charts. For that, you need to put the deployment packages in a persistent volume. This is described in the [spotfire-server chart](https://github.com/TIBCOSoftware/spotfire-cloud-deployment-kit/blob/main/helm/charts/spotfire-server/README.md) 

Check the variable `volumes.deployments.existingClaim`. And this is just an snippet example of what you would use in your `values.yaml`. Here my PV is called `local-pvc-deployment-areas`: 
```
  volumes:
    deployments:
      existingClaim: "local-pvc-deployment-areas"
```
Let me know if this helps

**Comment by alexandrev** [comment]
Thanks  @mdiez-tibco !

**Comment by alexandrev** [comment]
Clarification done.

**Comment by alexandrev** [comment]
I will reopen again after reviewing the chart. This is forcing now to be PVC claims. This is not the best way to do this kind of "provide data in advance" PVC is not the best way. Opening the option to be a ConfigMap should be much better, especially for the read-only kind of data. Because today there is no way to pre-populate a PVC without being mounted previously.

**Comment by mjohanss-tibco** [comment]
With the release of [version 1.2.0](https://github.com/TIBCOSoftware/spotfire-cloud-deployment-kit/releases/tag/v1.2.0) it adds the ability to automatically deploy Spotfire.Dxp.sdn automatically to a deployment area on helm installation, from the spotfire-server chart. By default it will create the deployment area 'Production' with Spotfire.Dxp.sdn on it.

Even though it does not add Spotfire.Dxp.netcore-linux.sdn we believe this should solve many cases to get a working Spotfire environment bootstrapped. If you want additional deployment areas or packages you can either create them manually using the web interface or configuration command line tool (config.sh) or as previously mentioned using a pre-populated PersistentVolume / PersistentVolumeClaim. Alternatively you can also create your own version of spotfire-deployment container (see containers/spotfire-deployment) with a custom set of sdn / spk packages on it. Note the image for spotfire-server's values.yaml `configuration.deployment.defaultDeployment` [can be overridden](https://github.com/TIBCOSoftware/spotfire-cloud-deployment-kit/blob/main/helm/charts/spotfire-server/values.yaml#L492-L510) to a customly built one. 

I think that pre-populating a PersistentVolume seems to be the most straight forward solution to add custom packages.

**Comment by alexandrev** [comment]
Hi Markus,

I think the approach that we're following for a lot of things focused on
"pre-existed persistent volume" is not aligned with best-practices. As is
not supporting GitOps approach and require manual intervention. I think the
approach should be in a different way. For some options we can rely on
ConfigMaps prepoulated, but for big binaries such as this, this is not a
valid option.

I don't think this should be close as the solution is quite manual at the
moment.

Regards,

 *Alexandre Vazquez *  |  *E * ***@***.***
***@***.***>*  | *W* https://alexandre-vazquez.com *|*

**Comment by mjohanss-tibco** [comment]
With release 1.2.0 the default sdn, Spotfire.Dxp.sdn, will be installed by default on a brand new installation without any prior spotfire database and that is the reason why the ticket was closed. I would prefer if we could handle additional bugs or improvements in a separate ticket. If there is something else to support can you provide some more information about these best practices you're referring to, what the different way of doing it would be, or exactly what problem that needs to be solved that does not currently have a well working solution.

To summarize, currently supported methods custom/additonal deployment files to be automatically added during helm install. (The standard Spotfire.Dxp.sdn client deployment is deployed by default)

- PersistentVolumeClaim - volumes.deployments.existingClaim - See [Manually creating a PersistentVolumeClaim and a PersistentVolume, binding them together, and referring to the PersistentVolumeClaim in a Pod specification.](https://cloud.google.com/kubernetes-engine/docs/how-to/persistent-volumes/preexisting-pd#pvc_to_pv) for an example how to create a PVC to use as an existingClaim
- initContainer option 1 - configuration.deployment.defaultDeployment.image - override this image, see containers/spotfire-deployment for how such a container image can be created
- initContainer option 2 - configJob.extraInitContainers - You can create an init container that copies files to /opt/tibco/spotfireconfigtool/deployments into the configJob container, see [Volume for deploying SDNs/SPKs](https://github.com/TIBCOSoftware/spotfire-cloud-deployment-kit/tree/main/helm/charts/spotfire-server#volume-for-deploying-sdnsspks)
- volumeMount - configJob.extraVolumes + configJob.extraVolumeMounts - inject an extra volume and volumeMount to populate /opt/tibco/spotfireconfigtool/deployments

Note: The Spotfire.Dxp.sdn is 387MB and it will not fit into a [ConfigMap](https://kubernetes.io/docs/concepts/configuration/configmap/) and it would also have the same requirement as with a volume that it needs to be pre-populated. Because "The data stored in a ConfigMap cannot exceed 1 MiB." it makes it unfit for storing packages.
