### ISSUE TITLE
volumes.deployments.existingClaim doesn't actually add packages to the Deployment area

### ISSUE THREAD

**Issue by sjkingo** [TIBCOSoftware/spotfire-cloud-deployment-kit#5]
I'm having a trouble with the `volumes.deployments.existingClaim` value for the spotfire-server chart. I have added a `.sdn` and `.spk` file to the volume in the format: `Test/[files]`. I expect these to be added to a new (or updated) deployment area. The configJob script appears to pick up the files and spends 8 minutes running with the following output:

![image](https://user-images.githubusercontent.com/476440/188791125-21a59725-02a9-4c2d-8202-162940254f27.png)

The job completes successfully:

![image](https://user-images.githubusercontent.com/476440/188791210-f12b3705-8eb7-4b29-83e0-d2770f6db75c.png)

The deployment area is created, but there are no packages in it:

![image](https://user-images.githubusercontent.com/476440/188791399-d3b8238f-dc81-4654-a643-83bda5e8e4fc.png)

When I manually Add packages and select the two files, it works as expected. Deleting the area after the job completes takes a few minutes, whereas deleting a newly created area is instant.

Am I missing something here? Maybe a metadata update command not being run in the job?

Building the helm charts off the latest master with Spotfire 12.0.

Thanks

**Comment by sjkingo** [comment]
Please ignore - after about 2-3 hours the packages appeared, though I couldn't find any logs showing this was a queued/offline operation.

**Comment by mdiez-tibco** [comment]
Hi @sjkingo, 

From our experience, using the default sdn files, in small environments it takes ~10min.

Anyhow, it shouldn't take 2-3 hours to see the packages in the deployment area. Could it be environment related? Does it take the same time as well for the default deployment area? Does it take the same time without your custom .spk file? 

I marked the issue as invalid due to the issue tittle. I will close the issue now. But, please, feel free to create a new issue with more information if you confirm that deploying the sdn files in the deployment areas take longer than 10-20 min (it may depend on your environment) using only the standard sdn files.

Thanks
